### ISSUE TITLE
Support all fields in `alertmanager`-spec

### ISSUE THREAD

**Issue by henrikhorluck** [nais/liberator#22]
In `alerterator` we currently only support a few of the available fields in `alertmanager`. We added `group_by` in #21, and it would be useful to also have e.g. `mute_time_interval`. Therefore it might be beneficial to instead reference the `alertmanager`-types directly — staying DRY `liberator`.

See: [alertmanager](https://github.com/prometheus/alertmanager/blob/e3fb99cc2d24330fdb81aa1d466c19b3de328b5b/config/config.go#L659) for the type-definitions

**Comment by Kyrremann** [comment]
Slik vi nå autogenerer dokumentasjon basert på kommentarer til de forskjellige `struct`-ene så blir dokumentasjonen vår veldig rotete, og vi får heller ikke spesifisert noe selv. Så løsningen ble å bruke så mye som mulig, men ikke en direkte import.
Kan se mer om det her: https://github.com/nais/alerterator/pull/43
